### ISSUE TITLE
Creating the Farm Role - ERROR

### ISSUE THREAD

**Issue by lcc2207** [momohawari/kitchen-scalr#1]
We are running into issues where kitchen will fail on 'Creating the Farm Role'

output of kitchen
-----> Creating <default-CentOS7>...
       Creating farm with name: KITCHEN_FARM_default-CentOS7_xxxxxx-xxx
       Success: farmId is 1111
       Getting the imageId for image CentOS7-Linux-November-2016
       The image id is xxxxxxxxxxxxxxxx
       The image os id is centos-7-x
       The image platform is ec2
       The image Location is us-east-1
       Creating a role with name KITCHEN-ROLE-xxxxxxxxxxxxx
       The role id is 1234
       RoleImage association created
       Creating the Farm Role
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [409 Conflict] on default-CentOS7

**Comment by mhawari** [comment]
Hello,
What version of Scalr are you running? Could you join a safe version of your kitchen.yml file?

**Comment by lcc2207** [comment]
Scalr version 7.4. 
CLI version 1.0.49
I not sure I understand the kitchen.yml question.

**Comment by mhawari** [comment]
Oh sorry, I was asking you to attach the kitchen.yml file (sanitized so that you don't leak any internal information) so that we could take a look at the config and understand the issue.

**Comment by lcc2207** [comment]
---
driver:
  name: scalr

provisioner:
  name: chef_zero

platforms:
  - name: CentOS7
    driver:
      scalr_api_url: 'https://xxx.xx.com'
      scalr_env_id: '1'
      scalr_project_id: 'x5xxxxxx'
      scalr_server_image: CentOS7-Linux
      scalr_location: 'us-east-1'
      scalr_server_instanceType: 'm3.medium'
      scalr_platform: 'ec2'

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:

**Comment by mhawari** [comment]
Wild guess: any policy enforcement on the environment you use?

**Comment by lcc2207** [comment]
the only policy we have is forcing the AWS build to specific VPC

**Comment by mhawari** [comment]
Ok thanks for raising the issue. VPC are not currently handled by the plugin, and we are waiting for the next Scalr release to implement this support along with multi-cloud support. Please verify that everything is working when this policy is not enforced, we will add support for VPC in the following releases of kitchen-scalr.

**Comment by lcc2207** [comment]
any eta on when all of that will hit?

**Comment by mhawari** [comment]
Nothing accurate yet, a few weeks probably.

**Comment by mhawari** [comment]
Ok it was way shorter actually. It should work with Scalr 7.5 and kitchen-scalr 0.2.0. We introduced the scalr_base_farm_role configuration parameter in the kitchen.yml file that should allow you to put a VPC with something like:
driver:
  name: scalr

provisioner:
  name: chef_zero

platforms:

  - name: CentOS7
    driver:
      scalr_api_url: 'https://xxx.xx.com'
      scalr_env_id: '1'
      scalr_project_id: 'x5xxxxxx'
      scalr_server_image: CentOS7-Linux
      scalr_location: 'us-east-1'
      scalr_server_instanceType: 'm3.medium'
      scalr_platform: 'ec2'
      scalr_base_farm_role:
        networking:
          networks:
          - id: 'some-id-specific-to-vpc'
suites:
  - name: default
     run_list:
     recipe[test::default]
     attributes:

The network id can be retrieved by using `scalr-ctl farm-roles get` with an existing farm-role that is configured with the right VPC.

Closing the ticket now
